name: ninja_basex
description: Convert data to any base (base32, base64, base58, etc) using an alphabet set. Supports disabling padding.
version: 1.0.2
homepage: https://github.com/ninja-dart/basex

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  ninja:
